export const SET_AUTH = "SET_AUTH";
export const SET_UNAUTH = "SET_UNAUTH";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const CHANGE_AVATAR = "CHANGE_AVATAR";
export const CHANGE_AVATAR_ERROR = "CHANGE_AVATAR_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_POSTS = "GET_POSTS";
export const LOADING_POSTS = "LOADING_POSTS";

export const GET_POST = "GET_POST";
export const LOADING_POST = "LOADING_POST";

export const LOADING_USER_BY_HANDLE = "LOADING_USER_BY_HANDLE";
export const GET_USER_BY_HANDLE = "GET_USER_BY_HANDLE";
export const CLEAR_SELECTED_USER = "CLEAR_SELECTED_USER";

export const CREATING_POST = "CREATING_POST";
export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";
export const LOADING_POSTS_ERROR = "LOADING_POSTS_ERROR";
export const DELETE_POST = "DELETE_POST";
export const CREATE_POST = "CREATE_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADDING_COMMENT = "ADDING_COMMENT";
export const CLEAR_SELECTED_POST = "CLEAR_SELECTED_POST";